export const TOOL_CATEGORIES = ['image', 'color', 'text', 'dev'] as const

export type ToolCategory = (typeof TOOL_CATEGORIES)[number]

export type ToolCategoryFilter = ToolCategory | 'all'

export const TOOL_CATALOG = [
  {
    id: 'dummy-image',
    num: '01',
    tag: '#image · #placeholder',
    category: 'image',
    href: '/tools/dummy-image',
    titleKey: 'dummyImage.title',
    descriptionKey: 'dummyImage.description',
    homeDescriptionKey: 'dummyImage.description',
    enabled: true,
  },
  {
    id: 'image-converter',
    num: '02',
    tag: '#image · #convert',
    category: 'image',
    href: '/tools/image-converter',
    titleKey: 'imageConverter.title',
    descriptionKey: 'imageConverter.description',
    homeDescriptionKey: 'imageConverter.description',
    enabled: true,
  },
  {
    id: 'image-compressor',
    num: '03',
    tag: '#image · #optimize',
    category: 'image',
    href: '/tools/image-compressor',
    titleKey: 'imageCompressor.title',
    descriptionKey: 'imageCompressor.description',
    homeDescriptionKey: 'imageCompressor.description',
    enabled: true,
  },
  {
    id: 'image-resizer',
    num: '04',
    tag: '#image · #resize',
    category: 'image',
    href: '/tools/image-resizer',
    titleKey: 'imageResizer.title',
    descriptionKey: 'imageResizer.description',
    homeDescriptionKey: 'imageResizer.description',
    enabled: true,
  },
  {
    id: 'color-converter',
    num: '05',
    tag: '#color · #convert',
    category: 'color',
    href: '/tools/color-converter',
    titleKey: 'colorConverter.title',
    descriptionKey: 'colorConverter.description',
    homeDescriptionKey: 'colorConverter.description',
    enabled: true,
  },
  {
    id: 'encoder-decoder',
    num: '06',
    tag: '#text · #encode',
    category: 'text',
    href: '/tools/encoder-decoder',
    titleKey: 'encoderDecoder.title',
    descriptionKey: 'encoderDecoder.description',
    homeDescriptionKey: 'encoderDecoder.description',
    enabled: true,
  },
  {
    id: 'json-formatter',
    num: '07',
    tag: '#dev · #json',
    category: 'dev',
    href: '/tools/json-formatter',
    titleKey: 'jsonFormatter.title',
    descriptionKey: 'jsonFormatter.description',
    homeDescriptionKey: 'jsonFormatter.description',
    enabled: true,
  },
  {
    id: 'timestamp-converter',
    num: '08',
    tag: '#dev · #time',
    category: 'dev',
    href: '/tools/timestamp-converter',
    titleKey: 'timestampConverter.title',
    descriptionKey: 'timestampConverter.description',
    homeDescriptionKey: 'timestampConverter.description',
    enabled: true,
  },
  {
    id: 'character-counter',
    num: '09',
    tag: '#text · #count',
    category: 'text',
    href: '/tools/character-counter',
    titleKey: 'characterCounter.title',
    descriptionKey: 'characterCounter.description',
    homeDescriptionKey: 'characterCounter.description',
    enabled: true,
  },
  {
    id: 'dummy-text',
    num: '10',
    tag: '#text · #placeholder',
    category: 'text',
    href: '/tools/dummy-text',
    titleKey: 'dummyText.title',
    descriptionKey: 'dummyText.description',
    homeDescriptionKey: 'dummyText.description',
    enabled: true,
  },
] as const

export type ToolCatalogItem = (typeof TOOL_CATALOG)[number]
